const version = '/v1';

export const API = {
  USER: version + '/user',
  LOGIN: version + '/login',
  AUTH: version + '/auth',
  // "REGISTER": version + '/register',
  LOGOUT: version + '/logout',
  COPY_PLAN: version + '/plans/copy/',
  SETTINGS: version + '/settings',
  STUDY_TERMS: version + '/study-terms',
  FORM_STUDIES: version + '/form-studies',
  FORM_ORGANIZATIONS: version + '/form-organizations',
  FORM_CONTROLS: version + '/form-controls',
  INDIVIDUAL_TASKS: version + '/individual-tasks',
  PLAN_CREATE: version + '/plans/additional-data',
  PLANS: version + '/plans',
  DEPARTMENTS: version + '/departments',
  USERS: version + '/users',
  FACULTIES: version + '/faculties',
  ROLES: version + '/roles',
  WORKERS: version + '/workers',
  LIST_WORKERS: version + '/list-workers',
  FACULTY_BY_WORKER: version + '/faculty-by-worker',
  SELECTIVE_DISCIPLINES: version + '/selective-discipline',
  CYCLES: version + '/cycles',
  SUBJECTS: version + '/subjects',
  PLAN_VERIFICATION: version + '/plans/verification',
  PLAN_VERIFICATION_OP: version + '/plans/verification-op',
  PLAN_FILTERS: version + '/plans/filters',
  VERIFICATIONS: version + '/verifications',
  VERIFICATION_SUBJECT_STATUSES: version + '/verification-subject-statuses',
  SPECIALIZATIONS: version + '/specializations',
  SPECIALITIES: version + '/specialities',
  EDUCATIONAL_PROGRAMS: version + '/education-programs',
  POSITIONS: version + '/positions',
  SIGNATURES: version + '/signatures',
  NOTES: version + '/notes',
  LIST_CYCLES: version + '/list-cycles',
  PROGRAMS: version + '/programs',
  USER_ACTIVITY: version + '/user-activity',
  SUBJECT_HELPERS: version + '/subject-helpers',
  CATALOG_HELPER_TYPES: version + '/catalog-helper-types',
  SUBJECT_LANGUAGES: version + '/subject-languages',
  CATALOG_GROUPS: version + '/catalog-groups',
  CATALOG_GROUPS_RESTORE: version + '/catalog-groups/restore',
  CATALOG_SELECTIVE_SUBJECTS: version + '/catalog-selective-subjects',
  CATALOG_SELECTIVE_SUBJECTS_FILTERS: version + '/catalog-selective-subjects/filters',
  CATALOG_SUBJECTS: version + '/catalog-subjects',
  CATALOG_SUBJECTS_TITLES: version + '/catalog-subjects/catalog-titles',
  EDUCATIONAL_PROGRAMS_ALL: version + '/education-programs',
  SPECIALITIES_ALL: version + '/specialities',
  CATALOG_SUBJECTS_GENERATE_PDF: version + '/catalog-subjects/generate-pdf',
  CATALOG_SPECIALTIES: version + '/catalog-specialties',
  CATALOG_SPECIALTIES_FILTERS: version + '/catalog-specialties/filters',
  CATALOG_SPECIALTIES_COPY: version + '/catalog-specialties/copy',
  SPECIALTY_SUBJECTS: version + '/speciality-subjects',
  SAVE_SPECIALITY_OWNERS: version + '/catalog-specialties/owners',
  SAVE_SPECIALITY_SIGNATURE: version + '/catalog-specialties/signature',

  ERR: version + '/err',
};

export const ALLOWED_REQUEST_PARAMETERS = {
  GET_PLANS: {
    itemsPerPage: 'items_per_page',
    page: 'page',
    searchTitle: 'title',
    sortBy: 'sort_by',
    sortDesc: 'sort_desc',
    faculty: 'faculty',
    department: 'department',
    divisionWithStatus: 'divisionWithStatus',
  },
  GET_LOGS: {
    itemsPerPage: 'items_per_page',
    page: 'page',
  },
  GET_USERS: {
    itemsPerPage: 'items_per_page',
    page: 'page',
  },
  GET_SUBJECT_HELPERS: {
    itemsPerPage: 'items_per_page',
    page: 'page',
    searchTitle: 'title',
    type: 'type',
  },
  GET_CATALOG_GROUPS: {
    itemsPerPage: 'items_per_page',
    page: 'page',
  },
  GET_CATALOG_SELECTIVE_SUBJECTS: {
    itemsPerPage: 'items_per_page',
    page: 'page',
    year: 'year',
    group: 'group',
    faculty: 'faculty',
    department: 'department',
    divisionWithStatus: 'divisionWithStatus',
  },
  GET_CATALOG_SELECTIVE_SUBJECTS_PDF: {
    year: 'year',
    group: 'group_id',
    faculty: 'faculty',
    department: 'department',
  },
  GET_CATALOG_SUBJECTS: {
    itemsPerPage: 'items_per_page',
    page: 'page',
    year: 'year',
    group: 'group',
  },
  GET_CATALOG_SPECIALTIES: {
    itemsPerPage: 'items_per_page',
    page: 'page',
    year: 'year',
    speciality: 'speciality',
    faculty: 'faculty',
    department: 'department',
    divisionWithStatus: 'divisionWithStatus',
  },
  SPECIALTY_SUBJECTS: {
    itemsPerPage: 'items_per_page',
    page: 'page',
    year: 'year',
    speciality: 'speciality',
    faculty: 'faculty',
    department: 'department',
    catalogSubject: 'catalogSubject',
    divisionWithStatus: 'divisionWithStatus',
  },
};
